exclude: |
  (?x)^(
    vendor/.*
  )$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: cicd/deploy/charts/.*?/templates
    args:
    - --allow-multiple-documents
