name: Label

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
    - master
    - "!deps/**"

jobs:
  label:
    if: "!startsWith(github.head_ref, 'refs/heads/deps')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
